# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b5830c1e2dbbaee3d340dab9212de4883bdbc3249537b2a9709fc9d8adf7f6a5d3fc1ae7549cf5b3996524e342bfffba09c41bdf031f56658f99cc50d838c16

test:
  secret_key_base: 0d6adf3230ee0eebeeaf5e5d1c09f64869e104989e4250f75e2400a843d952b2c5f539c52f8afbe9ce1244f8ca42a89303726610392fc97539383552acdab0dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
